version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-ishiko:1.0.0
    steps:
      - checkout:
          path: /DiplodocusDB/Core
      - run:
          name: Build
          command: cd /DiplodocusDB/Core/Makefiles/GNUmakefile && make
